name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn typecheck

      - name: Unit tests
        run: yarn test --runInBand

      - name: Prepare Mastra home
        run: mkdir -p .mastra-home

      - name: Mastra lint (non-blocking)
        run: HOME="$PWD/.mastra-home" npx mastra lint --dir src/mastra || true

      - name: Build diff summary
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --stat origin/${{ github.base_ref }}... > mastra-report.md
          echo -e "\n### Notes\n- [ ] TODO: 替换为 Mastra 生成的评审内容" >> mastra-report.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MASRA_GITHUB_TOKEN || github.token }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('mastra-report.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
